project_name: aura
dist: dist

gomod:
  proxy: true

builds:
  - main: ./cmd/aura
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - format: binary

changelog:
  skip: true

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

release:
  disable: true

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - "aura:{{ .Version }}"
      - "aura:latest"

snapshot:
  name_template: "dev"
